// ข้อมูลตัวอักษรจีนพื้นฐาน (แบบง่าย/Simplified) พร้อมพินอิน แบ่งตามกลุ่ม
const CHINESE_DATA = [
  // --- ตัวเลข 1-10 ---
  { char: "一", reading: "yī", group: "numbers" },
  { char: "二", reading: "èr", group: "numbers" },
  { char: "三", reading: "sān", group: "numbers" },
  { char: "四", reading: "sì", group: "numbers" },
  { char: "五", reading: "wǔ", group: "numbers" },
  { char: "六", reading: "liù", group: "numbers" },
  { char: "七", reading: "qī", group: "numbers" },
  { char: "八", reading: "bā", group: "numbers" },
  { char: "九", reading: "jiǔ", group: "numbers" },
  { char: "十", reading: "shí", group: "numbers" },

  // --- อักษรพื้นฐาน (basic) ---
  { char: "人", reading: "rén", group: "basic" },
  { char: "大", reading: "dà", group: "basic" },
  { char: "小", reading: "xiǎo", group: "basic" },
  { char: "中", reading: "zhōng", group: "basic" },
  { char: "上", reading: "shàng", group: "basic" },
  { char: "下", reading: "xià", group: "basic" },
  { char: "口", reading: "kǒu", group: "basic" },
  { char: "日", reading: "rì", group: "basic" },
  { char: "月", reading: "yuè", group: "basic" },
  { char: "水", reading: "shuǐ", group: "basic" },
  { char: "火", reading: "huǒ", group: "basic" },
  { char: "木", reading: "mù", group: "basic" },
  { char: "山", reading: "shān", group: "basic" },
  { char: "田", reading: "tián", group: "basic" },
  { char: "目", reading: "mù", group: "basic" },
  { char: "女", reading: "nǚ", group: "basic" },
  { char: "子", reading: "zǐ", group: "basic" },
  { char: "手", reading: "shǒu", group: "basic" },
  { char: "心", reading: "xīn", group: "basic" },
  { char: "耳", reading: "ěr", group: "basic" },
  { char: "力", reading: "lì", group: "basic" },
  { char: "刀", reading: "dāo", group: "basic" },
  { char: "门", reading: "mén", group: "basic" },
  { char: "天", reading: "tiān", group: "basic" },
  { char: "地", reading: "dì", group: "basic" },
  { char: "我", reading: "wǒ", group: "basic" },
  { char: "你", reading: "nǐ", group: "basic" },
  { char: "他", reading: "tā", group: "basic" },
  { char: "好", reading: "hǎo", group: "basic" },
  { char: "是", reading: "shì", group: "basic" },
  { char: "不", reading: "bù", group: "basic" },
  { char: "了", reading: "le", group: "basic" },
  { char: "的", reading: "de", group: "basic" },
  { char: "在", reading: "zài", group: "basic" },
  { char: "有", reading: "yǒu", group: "basic" },
  { char: "猫", reading: "māo", group: "basic" },
  { char: "狗", reading: "gǒu", group: "basic" },
  { char: "鱼", reading: "yú", group: "basic" },
  { char: "鸟", reading: "niǎo", group: "basic" },
  { char: "花", reading: "huā", group: "basic" },
  { char: "车", reading: "chē", group: "basic" },
  { char: "书", reading: "shū", group: "basic" },

  // --- คำศัพท์พื้นฐาน 2 ตัวอักษร (words) ---
  { char: "你好", reading: "nǐ hǎo", group: "words" },
  { char: "谢谢", reading: "xiè xie", group: "words" },
  { char: "再见", reading: "zài jiàn", group: "words" },
  { char: "朋友", reading: "péng you", group: "words" },
  { char: "学生", reading: "xué sheng", group: "words" },
  { char: "老师", reading: "lǎo shī", group: "words" },
  { char: "爸爸", reading: "bà ba", group: "words" },
  { char: "妈妈", reading: "mā ma", group: "words" },
  { char: "中国", reading: "zhōng guó", group: "words" },
  { char: "天气", reading: "tiān qì", group: "words" },
  { char: "时间", reading: "shí jiān", group: "words" },
  { char: "学校", reading: "xué xiào", group: "words" },
  { char: "医生", reading: "yī shēng", group: "words" },
  { char: "苹果", reading: "píng guǒ", group: "words" },
  { char: "香蕉", reading: "xiāng jiāo", group: "words" },
  { char: "熊猫", reading: "xióng māo", group: "words" },
  { char: "电脑", reading: "diàn nǎo", group: "words" },
  { char: "手机", reading: "shǒu jī", group: "words" },
  { char: "音乐", reading: "yīn yuè", group: "words" },
];
