// ข้อมูลตัวอักษรจีนพื้นฐาน (แบบง่าย/Simplified) พร้อมพินอิน แบ่งตามกลุ่ม
const CHINESE_DATA = [
  // --- ตัวเลข 1-10 ---
  { char: "一", reading: "yī", group: "numbers" },
  { char: "二", reading: "èr", group: "numbers" },
  { char: "三", reading: "sān", group: "numbers" },
  { char: "四", reading: "sì", group: "numbers" },
  { char: "五", reading: "wǔ", group: "numbers" },
  { char: "六", reading: "liù", group: "numbers" },
  { char: "七", reading: "qī", group: "numbers" },
  { char: "八", reading: "bā", group: "numbers" },
  { char: "九", reading: "jiǔ", group: "numbers" },
  { char: "十", reading: "shí", group: "numbers" },

  // --- อักษรพื้นฐาน (basic) ---
  { char: "人", reading: "rén", group: "basic" },
  { char: "大", reading: "dà", group: "basic" },
  { char: "小", reading: "xiǎo", group: "basic" },
  { char: "中", reading: "zhōng", group: "basic" },
  { char: "上", reading: "shàng", group: "basic" },
  { char: "下", reading: "xià", group: "basic" },
  { char: "口", reading: "kǒu", group: "basic" },
  { char: "日", reading: "rì", group: "basic" },
  { char: "月", reading: "yuè", group: "basic" },
  { char: "水", reading: "shuǐ", group: "basic" },
  { char: "火", reading: "huǒ", group: "basic" },
  { char: "木", reading: "mù", group: "basic" },
  { char: "山", reading: "shān", group: "basic" },
  { char: "田", reading: "tián", group: "basic" },
  { char: "目", reading: "mù", group: "basic" },
  { char: "女", reading: "nǚ", group: "basic" },
  { char: "子", reading: "zǐ", group: "basic" },
  { char: "手", reading: "shǒu", group: "basic" },
  { char: "心", reading: "xīn", group: "basic" },
  { char: "耳", reading: "ěr", group: "basic" },
  { char: "力", reading: "lì", group: "basic" },
  { char: "刀", reading: "dāo", group: "basic" },
  { char: "门", reading: "mén", group: "basic" },
  { char: "天", reading: "tiān", group: "basic" },
  { char: "地", reading: "dì", group: "basic" },
  { char: "我", reading: "wǒ", group: "basic" },
  { char: "你", reading: "nǐ", group: "basic" },
  { char: "他", reading: "tā", group: "basic" },
  { char: "好", reading: "hǎo", group: "basic" },
  { char: "是", reading: "shì", group: "basic" },
  { char: "不", reading: "bù", group: "basic" },
  { char: "了", reading: "le", group: "basic" },
  { char: "的", reading: "de", group: "basic" },
  { char: "在", reading: "zài", group: "basic" },
  { char: "有", reading: "yǒu", group: "basic" },
  { char: "猫", reading: "māo", group: "basic" },
  { char: "狗", reading: "gǒu", group: "basic" },
  { char: "鱼", reading: "yú", group: "basic" },
  { char: "鸟", reading: "niǎo", group: "basic" },
  { char: "花", reading: "huā", group: "basic" },
  { char: "车", reading: "chē", group: "basic" },
  { char: "书", reading: "shū", group: "basic" },

  // --- คำศัพท์พื้นฐาน 2 ตัวอักษร (words) ---
  { char: "你好", reading: "nǐ hǎo", group: "words" },
  { char: "谢谢", reading: "xiè xie", group: "words" },
  { char: "再见", reading: "zài jiàn", group: "words" },
  { char: "朋友", reading: "péng you", group: "words" },
  { char: "学生", reading: "xué sheng", group: "words" },
  { char: "老师", reading: "lǎo shī", group: "words" },
  { char: "爸爸", reading: "bà ba", group: "words" },
  { char: "妈妈", reading: "mā ma", group: "words" },
  { char: "中国", reading: "zhōng guó", group: "words" },
  { char: "天气", reading: "tiān qì", group: "words" },
  { char: "时间", reading: "shí jiān", group: "words" },
  { char: "学校", reading: "xué xiào", group: "words" },
  { char: "医生", reading: "yī shēng", group: "words" },
  { char: "苹果", reading: "píng guǒ", group: "words" },
  { char: "香蕉", reading: "xiāng jiāo", group: "words" },
  { char: "熊猫", reading: "xióng māo", group: "words" },
  { char: "电脑", reading: "diàn nǎo", group: "words" },
  { char: "手机", reading: "shǒu jī", group: "words" },
  { char: "音乐", reading: "yīn yuè", group: "words" },

  // --- คำศัพท์ระดับ HSK5 (คัดสรรคำที่พบบ่อย ไม่ใช่รายการทางการฉบับเต็ม) ---
  { char: "经济", reading: "jīng jì", group: "hsk5" },
  { char: "环境", reading: "huán jìng", group: "hsk5" },
  { char: "压力", reading: "yā lì", group: "hsk5" },
  { char: "效率", reading: "xiào lǜ", group: "hsk5" },
  { char: "竞争", reading: "jìng zhēng", group: "hsk5" },
  { char: "合作", reading: "hé zuò", group: "hsk5" },
  { char: "责任", reading: "zé rèn", group: "hsk5" },
  { char: "态度", reading: "tài du", group: "hsk5" },
  { char: "习惯", reading: "xí guàn", group: "hsk5" },
  { char: "经验", reading: "jīng yàn", group: "hsk5" },
  { char: "机会", reading: "jī huì", group: "hsk5" },
  { char: "挑战", reading: "tiǎo zhàn", group: "hsk5" },
  { char: "成功", reading: "chéng gōng", group: "hsk5" },
  { char: "失败", reading: "shī bài", group: "hsk5" },
  { char: "目标", reading: "mù biāo", group: "hsk5" },
  { char: "计划", reading: "jì huà", group: "hsk5" },
  { char: "决定", reading: "jué dìng", group: "hsk5" },
  { char: "建议", reading: "jiàn yì", group: "hsk5" },
  { char: "影响", reading: "yǐng xiǎng", group: "hsk5" },
  { char: "改变", reading: "gǎi biàn", group: "hsk5" },
  { char: "发展", reading: "fā zhǎn", group: "hsk5" },
  { char: "提高", reading: "tí gāo", group: "hsk5" },
  { char: "增加", reading: "zēng jiā", group: "hsk5" },
  { char: "减少", reading: "jiǎn shǎo", group: "hsk5" },
  { char: "解决", reading: "jiě jué", group: "hsk5" },
  { char: "讨论", reading: "tǎo lùn", group: "hsk5" },
  { char: "研究", reading: "yán jiū", group: "hsk5" },
  { char: "调查", reading: "diào chá", group: "hsk5" },
  { char: "报告", reading: "bào gào", group: "hsk5" },
  { char: "参加", reading: "cān jiā", group: "hsk5" },
  { char: "举行", reading: "jǔ xíng", group: "hsk5" },
  { char: "活动", reading: "huó dòng", group: "hsk5" },
  { char: "表演", reading: "biǎo yǎn", group: "hsk5" },
  { char: "表示", reading: "biǎo shì", group: "hsk5" },
  { char: "表达", reading: "biǎo dá", group: "hsk5" },
  { char: "交流", reading: "jiāo liú", group: "hsk5" },
  { char: "联系", reading: "lián xì", group: "hsk5" },
  { char: "关系", reading: "guān xì", group: "hsk5" },
  { char: "感情", reading: "gǎn qíng", group: "hsk5" },
  { char: "情况", reading: "qíng kuàng", group: "hsk5" },
  { char: "状态", reading: "zhuàng tài", group: "hsk5" },
  { char: "条件", reading: "tiáo jiàn", group: "hsk5" },
  { char: "阶段", reading: "jiē duàn", group: "hsk5" },
  { char: "过程", reading: "guò chéng", group: "hsk5" },
  { char: "结果", reading: "jié guǒ", group: "hsk5" },
  { char: "原因", reading: "yuán yīn", group: "hsk5" },
  { char: "理由", reading: "lǐ yóu", group: "hsk5" },
  { char: "意见", reading: "yì jiàn", group: "hsk5" },
  { char: "价值", reading: "jià zhí", group: "hsk5" },
  { char: "价格", reading: "jià gé", group: "hsk5" },
  { char: "质量", reading: "zhì liàng", group: "hsk5" },
  { char: "数量", reading: "shù liàng", group: "hsk5" },
  { char: "规模", reading: "guī mó", group: "hsk5" },
  { char: "范围", reading: "fàn wéi", group: "hsk5" },
  { char: "标准", reading: "biāo zhǔn", group: "hsk5" },
  { char: "水平", reading: "shuǐ píng", group: "hsk5" },
  { char: "能力", reading: "néng lì", group: "hsk5" },
  { char: "知识", reading: "zhī shi", group: "hsk5" },
  { char: "技术", reading: "jì shù", group: "hsk5" },
  { char: "科学", reading: "kē xué", group: "hsk5" },
  { char: "教育", reading: "jiào yù", group: "hsk5" },
  { char: "文化", reading: "wén huà", group: "hsk5" },
  { char: "传统", reading: "chuán tǒng", group: "hsk5" },
  { char: "现代", reading: "xiàn dài", group: "hsk5" },
  { char: "社会", reading: "shè huì", group: "hsk5" },
  { char: "政府", reading: "zhèng fǔ", group: "hsk5" },
  { char: "政策", reading: "zhèng cè", group: "hsk5" },
  { char: "制度", reading: "zhì dù", group: "hsk5" },
  { char: "法律", reading: "fǎ lǜ", group: "hsk5" },
  { char: "权利", reading: "quán lì", group: "hsk5" },
  { char: "义务", reading: "yì wù", group: "hsk5" },
  { char: "自由", reading: "zì yóu", group: "hsk5" },
  { char: "平等", reading: "píng děng", group: "hsk5" },
  { char: "和平", reading: "hé píng", group: "hsk5" },
  { char: "安全", reading: "ān quán", group: "hsk5" },
  { char: "危险", reading: "wēi xiǎn", group: "hsk5" },
  { char: "保护", reading: "bǎo hù", group: "hsk5" },
  { char: "破坏", reading: "pò huài", group: "hsk5" },
  { char: "污染", reading: "wū rǎn", group: "hsk5" },
  { char: "资源", reading: "zī yuán", group: "hsk5" },
  { char: "能源", reading: "néng yuán", group: "hsk5" },
  { char: "环保", reading: "huán bǎo", group: "hsk5" },
  { char: "节约", reading: "jié yuē", group: "hsk5" },
  { char: "浪费", reading: "làng fèi", group: "hsk5" },
  { char: "消费", reading: "xiāo fèi", group: "hsk5" },
  { char: "生产", reading: "shēng chǎn", group: "hsk5" },
  { char: "企业", reading: "qǐ yè", group: "hsk5" },
  { char: "公司", reading: "gōng sī", group: "hsk5" },
  { char: "市场", reading: "shì chǎng", group: "hsk5" },
  { char: "投资", reading: "tóu zī", group: "hsk5" },
  { char: "收入", reading: "shōu rù", group: "hsk5" },
  { char: "成本", reading: "chéng běn", group: "hsk5" },
  { char: "利润", reading: "lì rùn", group: "hsk5" },
  { char: "贸易", reading: "mào yì", group: "hsk5" },
  { char: "出口", reading: "chū kǒu", group: "hsk5" },
  { char: "进口", reading: "jìn kǒu", group: "hsk5" },
  { char: "竞赛", reading: "jìng sài", group: "hsk5" },
];
